version: "3.8"

services:
  web:
    build:
      context: .
      args:
        GIT_TOKEN: ${GIT_TOKEN}
        REPO_URL: ${REPO_URL}
        BRANCH: ${BRANCH}
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MODEL_PATH=${MODEL_PATH}
      - DATA_DIR=${DATA_DIR}
      - IMG_HEIGHT=${IMG_HEIGHT}
      - IMG_WIDTH=${IMG_WIDTH}
      - BATCH_SIZE=${BATCH_SIZE}
      - EPOCHS=${EPOCHS}
      - LABELS_PATH=${LABELS_PATH}
      - STATUS_PATH=${STATUS_PATH}
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
